[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "dist/**"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL,VITE_SUPABASE_STORAGE_URL,VITE_SUPABASE_STORAGE_BUCKET,VITE_SUPABASE_STORAGE_REGION,RESEND_FROM_EMAIL,RESEND_API_KEY,SUPABASE_DIRECT_URL"

# Handle client-side routing for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
