import { Job } from '../types/job';

export const INITIAL_JOBS: Omit<Job, 'id'>[] = [
  {
    title: 'Senior Full Stack Cloud Engineer',
    slug: 'senior-full-stack-cloud-engineer-cloudscale',
    companyName: 'CloudScale Technologies',
    location: 'San Francisco, CA (Remote)',
    jobType: 'full-time',
    workArrangement: 'remote',
    category: 'Engineering',
    experienceLevel: 'senior',
    salaryMin: 155000,
    salaryMax: 195000,
    currency: 'USD',
    description: 'We are seeking an experienced Senior Full Stack Engineer to lead architecture across our distributed cloud platforms and serverless microservices. You will work on real-time event pipelines, modern TypeScript React interfaces, and resilient infrastructure.',
    responsibilities: '• Architect, build, and deploy high-throughput serverless microservices using TypeScript and Node.js.\n• Collaborate with product designers and frontend teams to implement accessible, ultra-responsive UI components.\n• Implement observability, automated integration testing, and CI/CD deployment pipelines.\n• Mentor junior and mid-level engineers through code reviews and technical design docs.',
    requirements: '• 5+ years of experience with React, TypeScript, and modern Node.js environments.\n• Deep expertise in serverless architectures, event-driven systems, and NoSQL databases.\n• Strong grasp of RESTful APIs, WebSockets, and state management.\n• Excellent communication skills in asynchronous remote environments.',
    benefits: '• 100% remote flexibility worldwide\n• Comprehensive health, dental, and vision insurance\n• $3,000 annual home office & learning stipend\n• Flexible paid time off (PTO) and company-wide recharge days\n• 401(k) matching up to 5%',
    applicationUrl: 'https://example.com/apply/senior-full-stack-engineer',
    applicationDeadline: '2026-11-30',
    tags: ['TypeScript', 'React', 'Node.js', 'Serverless', 'PostgreSQL'],
    status: 'published',
    featured: true,
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Senior Full Stack Cloud Engineer - Remote | CloudScale Technologies',
    seoDescription: 'Join CloudScale Technologies as a Senior Full Stack Cloud Engineer. Build distributed cloud platforms and serverless architectures with React and TypeScript.'
  },
  {
    title: 'Lead Product Designer',
    slug: 'lead-product-designer-aura-systems',
    companyName: 'Aura Systems',
    location: 'New York, NY',
    jobType: 'full-time',
    workArrangement: 'hybrid',
    category: 'Design',
    experienceLevel: 'lead',
    salaryMin: 140000,
    salaryMax: 175000,
    currency: 'USD',
    description: 'Aura Systems is building the next generation of creative productivity tools. We are looking for a Lead Product Designer to guide our end-to-end design system, conduct user research, and craft world-class desktop and mobile user experiences.',
    responsibilities: '• Define user journeys, wireframes, prototypes, and high-fidelity production designs.\n• Evolve and maintain our unified cross-platform design token system in Figma.\n• Partner closely with engineering leadership to ensure pixel-perfect, accessible implementations.\n• Conduct usability testing sessions and distill user feedback into actionable product roadmaps.',
    requirements: '• 6+ years designing consumer-facing or enterprise SaaS productivity applications.\n• Master-level proficiency in Figma, design systems, and prototyping tools.\n• Proven track record shipping products with clean typography, spacing discipline, and accessibility (WCAG AA).\n• Strong portfolio demonstrating problem-solving process and aesthetic precision.',
    benefits: '• Hybrid schedule (2 days in office, 3 days remote)\n• Premium health, vision, and mental wellness coverage\n• Competitive equity grant\n• Annual design conference travel budget',
    applicationUrl: 'https://example.com/apply/lead-product-designer',
    applicationDeadline: '2026-12-15',
    tags: ['Figma', 'Design Systems', 'UI/UX', 'Prototyping', 'Accessibility'],
    status: 'published',
    featured: true,
    createdAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 28).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Lead Product Designer - Hybrid (NYC) | Aura Systems',
    seoDescription: 'Exciting Lead Product Designer role at Aura Systems in New York. Lead design systems, prototyping, and user experience for modern SaaS tools.'
  },
  {
    title: 'Frontend Software Engineering Intern (Summer 2027)',
    slug: 'frontend-engineering-intern-syntax-labs',
    companyName: 'Syntax Labs',
    location: 'Austin, TX (Remote Available)',
    jobType: 'internship',
    workArrangement: 'remote',
    category: 'Engineering',
    experienceLevel: 'internship',
    salaryMin: 45,
    salaryMax: 55,
    currency: 'USD',
    description: 'Syntax Labs invites motivated students and early-career developers to join our 12-week paid engineering internship. You will contribute production code directly to our web applications, work alongside staff engineers, and gain hands-on experience with modern frontend workflows.',
    responsibilities: '• Develop customer-facing features using React 19, TypeScript, and Tailwind CSS.\n• Write automated unit and integration tests using Vitest and React Testing Library.\n• Participate in agile sprints, daily standups, and peer code reviews.\n• Present an end-of-internship capstone project to the company leadership.',
    requirements: '• Current student pursuing Computer Science or related degree, or equivalent self-taught/bootcamp experience.\n• Familiarity with JavaScript/TypeScript, HTML5, and CSS fundamentals.\n• Passion for building intuitive, accessible web interfaces.\n• Eagerness to learn and accept constructive feedback.',
    benefits: '• Competitive hourly pay ($45-$55/hr)\n• 1-on-1 mentorship with senior staff engineers\n• Equipment provided (MacBook Pro & peripherals)\n• Opportunity for full-time return offer upon graduation',
    applicationUrl: 'https://example.com/apply/frontend-internship-syntax',
    applicationDeadline: '2026-11-15',
    tags: ['React', 'TypeScript', 'TailwindCSS', 'Internship', 'Mentorship'],
    status: 'published',
    featured: true,
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Frontend Engineering Internship | Syntax Labs',
    seoDescription: 'Kickstart your tech career with Syntax Labs 12-week paid frontend engineering internship. Remote opportunity with competitive pay and mentorship.'
  },
  {
    title: 'Site Reliability & Infrastructure Specialist',
    slug: 'site-reliability-infrastructure-specialist-apex-cloud',
    companyName: 'Apex Data Networks',
    location: 'Chicago, IL',
    jobType: 'full-time',
    workArrangement: 'on-site',
    category: 'DevOps / SRE',
    experienceLevel: 'senior',
    salaryMin: 150000,
    salaryMax: 180000,
    currency: 'USD',
    description: 'We are seeking an on-site Site Reliability Engineer to manage our bare-metal and hybrid cloud infrastructure in our Chicago headquarters. You will oversee high-availability clusters, automated failovers, and low-latency network telemetry.',
    responsibilities: '• Manage Kubernetes clusters, edge ingress controllers, and multi-region network failover.\n• Implement zero-downtime deployment pipelines with Terraform and GitHub Actions.\n• Troubleshoot complex production incidents and conduct blame-free postmortems.\n• Partner with security officers to enforce zero-trust security architecture.',
    requirements: '• 4+ years in SRE, DevOps, or systems engineering roles.\n• Hands-on proficiency with Linux kernel tuning, Docker, and Kubernetes.\n• Experience with Infrastructure as Code (Terraform) and metrics telemetry (Prometheus, Grafana).\n• Ability to participate in a standard on-call rotation schedule.',
    benefits: '• Competitive base salary with annual performance bonus\n• On-site catered breakfast, lunch, and barista bar\n• Full medical, dental, and life insurance benefits\n• Commuter transit subsidy and on-site gym access',
    applicationUrl: 'https://example.com/apply/sre-apex-chicago',
    applicationDeadline: '2026-12-01',
    tags: ['Kubernetes', 'Linux', 'Terraform', 'Docker', 'Networking'],
    status: 'published',
    featured: false,
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Site Reliability Specialist - On-Site Chicago | Apex Data Networks',
    seoDescription: 'Join Apex Data Networks as an on-site Site Reliability Engineer in Chicago. Work with high-availability systems, Kubernetes, and telemetry.'
  },
  {
    title: 'Senior Technical Product Manager',
    slug: 'senior-technical-product-manager-vanguard-ai',
    companyName: 'Vanguard AI',
    location: 'Seattle, WA (Hybrid)',
    jobType: 'full-time',
    workArrangement: 'hybrid',
    category: 'Product',
    experienceLevel: 'senior',
    salaryMin: 160000,
    salaryMax: 200000,
    currency: 'USD',
    description: 'Vanguard AI is looking for an analytical, developer-centric Technical Product Manager to lead our API platform and developer tooling products. You will act as the bridge between engineering, customer solutions, and executive strategy.',
    responsibilities: '• Own the roadmap, specifications, and sprint priorities for our developer API ecosystem.\n• Analyze platform telemetry, API adoption metrics, and customer satisfaction.\n• Collaborate with engineering teams to scope technical requirements and delivery milestones.\n• Author developer documentation, changelogs, and release guides.',
    requirements: '• 4+ years of product management experience managing technical or API-driven SaaS products.\n• Prior background as a software developer or strong software engineering comprehension.\n• Demonstrated success delivering developer experience (DevEx) initiatives.\n• Exceptional written specification and stakeholder presentation abilities.',
    benefits: '• Flexible hybrid working arrangement\n• Health, dental, vision, and mental health stipends\n• 401(k) with company match\n• Generous parental leave policy',
    applicationUrl: 'https://example.com/apply/tpm-vanguard-ai',
    applicationDeadline: '2026-12-20',
    tags: ['Product Management', 'APIs', 'Developer Tools', 'Agile', 'Roadmapping'],
    status: 'published',
    featured: false,
    createdAt: new Date(Date.now() - 3600000 * 96).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 96).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 96).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Senior Technical Product Manager | Vanguard AI',
    seoDescription: 'Lead API developer platform roadmaps as Senior Technical Product Manager at Vanguard AI in Seattle.'
  },
  {
    title: 'Product Marketing & Growth Intern',
    slug: 'product-marketing-growth-intern-lumina',
    companyName: 'Lumina Health',
    location: 'Boston, MA (Hybrid)',
    jobType: 'internship',
    workArrangement: 'hybrid',
    category: 'Marketing',
    experienceLevel: 'internship',
    salaryMin: 32,
    salaryMax: 40,
    currency: 'USD',
    description: 'Join Lumina Health as a Product Marketing & Growth Intern. You will assist in launching go-to-market campaigns, writing compelling case studies, optimizing digital content for SEO, and analyzing user conversion funnels.',
    responsibilities: '• Draft engaging product updates, customer success stories, and blog posts.\n• Research competitive market trends and prepare intelligence briefings.\n• Assist with email marketing campaign setup and performance analytics.\n• Collaborate on landing page experimentation and conversion optimization.',
    requirements: '• College student or recent graduate in Marketing, Communications, Business, or related fields.\n• Strong writing and storytelling capabilities.\n• Basic familiarity with Google Analytics, SEO principles, and social media platforms.\n• High curiosity, proactiveness, and organizational skills.',
    benefits: '• Competitive hourly compensation ($32-$40/hr)\n• Flexible hybrid schedule in our vibrant Boston office\n• Direct exposure to executive marketing leaders\n• Potential path to full-time associate role',
    applicationUrl: 'https://example.com/apply/marketing-intern-lumina',
    applicationDeadline: '2026-11-20',
    tags: ['Marketing', 'SEO', 'Content Strategy', 'Growth', 'Internship'],
    status: 'published',
    featured: false,
    createdAt: new Date(Date.now() - 3600000 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 120).toISOString(),
    publishedAt: new Date(Date.now() - 3600000 * 120).toISOString(),
    createdBy: 'admin',
    seoTitle: 'Product Marketing & Growth Intern | Lumina Health',
    seoDescription: 'Gain hands-on experience in B2B healthtech marketing and SEO with Lumina Health in Boston.'
  }
];
